export const PLAY_TIMER = 'PLAY_TIMER';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const START_TIMER = 'START_TIMER';

export const EXCEED_TIME = 'EXCEED_TIME';
export const CLEAR_EXCEED_TIME = 'CLEAR_EXCEED_TIME';

export const CHANGE_START_TIME = 'CHANGE_START_TIME';